### ISSUE TITLE
Are you intending to release this module on cpan?

### ISSUE THREAD

**Issue by zdm** [Corion/AnyEvent-Impl-Prima#2]
Subj.

**Comment by Corion** [comment]
Yes, the medium term plan is to release it on CPAN. I have some doubts as to whether the module actually works in its current incarnation because it blocks when doing SSL requests. But that might be due to the nature of SSL / IO::Socket::SSL and not due to the nature of AnyEvent

But I need to look into it again before releasing, propably within the next three months.

If everything works out, this module might even simply become part of the AnyEvent distribution instead.

**Comment by zdm** [comment]
Perfect, thank you.

**Comment by dk** [comment]
Hello Max,

Any news on the cpan release? Anything I can help with?

Dmitry

**Comment by Corion** [comment]
Hi Dmitry,

no - I just revisited the code and I think I understand now why my HTTP 
tests are not to my liking. HTTPS does not work with select() on its 
sockets (obviously). I think I'll just release it and we can worry later 
with Marc on whether to include the module in AnyEvent proper or keep it 
separate.

If I get to it, I will do a release today (now-ish) or otherwise on 
Thursday / Friday next week, as starting tomorrow I'm organizer at the 
German Perl Workshop ...

-max

Am 24.06.2017 um 13:22 schrieb Dmitry Karasik:

**Comment by dk** [comment]
Ok that is understood, thank you! 

On the side node, SSL with select is working but is crazy (I've been bitten by it). It works like this: for example, you're getting a read bit set from select($ssl_socket) hinting that you need to sysread. Okay, you sysread - and getting an EWOULDBLOCK or EAGAIN! WTF? The trick is to check $SSL_ERROR variable - and in this case it very probably will be SSL_WANT_WRITE. That means that the internal mechanics of the ssl socket want you to enter select() again, but now waiting for write only (NOT read, otherwise you'll get same EWOULDBLOCK again). After that is done, you may proceed with reading. The situation is the same with SSL_WANT_READ when you're ready for syswrite. Hope this makes sense :)

**Comment by Corion** [comment]
It's now released as v0.01

I had to skip the tests for systems where `$ENV{ DISPLAY }` is not set, but I guess that's acceptable ;)
